import philipenes from "/images/card/philipenes.webp";
import japan2 from "/images/card/japan2.webp";
import japan from "/images/card/japan1.webp";
import australia from "/images/card/australia.webp";
import bali from "/images/card/bali2.webp";
import dubai from "/images/card/Dubai3n4dS.webp";
import france from "/images/card/France.webp";
import greece from "/images/card/greece.webp";;
import singapore from "/images/card/singapore4n5ds.webp";
import singapore2 from "/images/card/SMs.webp";
import swit from "/images/card/swit.webp";
import vietnam from "/images/card/vietnam4n5ds.webp";
import vietnam2 from "/images/card/vietnam6n7ds.webp";
import vietnam3 from "/images/card/vietnam9n10ds.webp";
import rj1 from "/images/card/rj1.webp";
import rj2 from "/images/card/rj2.webp";
import rj3 from "/images/card/rj3.webp";
import gujarat2 from "/images/card/gujarat2.webp";
import meghalaya from "/images/card/meghalaya.webp";
import shimla2 from "/images/card/shimla9n10d.webp";
import kerala from "/images/card/kerala.webp";
import andaman from "/images/card/andaman.webp";

export const internationalPackages = [
  {
    Name: "Bangkok & Pattaya",
    location: "BANGKOK & PATTAYA",
    title: "Explore Bangkok & Pattaya: A Vibrant Thai Adventure",
    duration: "5 Days & 4 Nights",
    rating: "4.8/5",
    cut_price: 25699,
    curr_price: 19999,
    save: 5700,
    direct: "/Thailand5d4n",
    image: "https://snowtailescapes.com/images/card/thailand4n5dS.webp",
    budget: 5,
  },
  {
    Name: "Phuket & Krabi",
    location: "PHUKET & KRABI",
    title: "Experience Best of Southern Thailand",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 36999,
    curr_price: 29999,
    // curr_price: 29699,
    save: 7000,
    direct: "/Thailand6d5n",
    image: "https://snowtailescapes.com/images/card/thailand5n6ds.webp",
    budget: 6,
  },
  {
    home: 1,
    Name: "Thailand",
    location: "PHUKET/KRABI/PATTAYA/BANGKOK",
    title: "Experience Jewels of Thailand",
    duration: "9 Days & 8 Nights",
    rating: "4.8/5",
    cut_price: 69099,
    curr_price: 59099,
    save: 10000,
    direct: "/Thailand9d8n",
    image: "https://snowtailescapes.com/images/card/thailand8n9ds.webp",
    country: "thailand",
  },
  {
    home: 2,
    Name: "Bali",
    location: "BALI",
    title: "Enchanting Bali Escape with Gili Island",
    duration: "8 Days & 7 Nights",
    rating: "4.8/5",
    cut_price: 64699,
    curr_price: 54699,
    save: 10000,
    direct: "/Bali8d7n",
    image: "https://snowtailescapes.com/images/card/Bali7n8ds.webp",
    country: "indonesia",
  },
  {
    direct: "/Bali6d5n",
    title: "Luxurious 6-Day Bali Honeymoon Escape: Kuta and Ubud Delights",
    curr_price: 34699,
    location: "BALI",
    duration: "5 nights 6 days tour",
    image: bali,
  },
  {
    direct: "/Vietnam4d5n",
    title: "Escape to North Vietnam: A Journey of Cultural Marvels",
    curr_price: 37699,
    location: "VIETNAM",
    duration: "4 nights 5 days tour",
    image: vietnam,
  },
  {
    direct: "/Vietnam6n7d",
    title: "Discover Vietnam: A Journey Through North & South Vietnam",
    curr_price: 57699,
    location: "VIETNAM",
    duration: "6 nights 7 days tour",
    image: vietnam2,
  },
  {
    direct: "/Vietnam9n10d",
    title: "Captivating Vietnam: A Journey Through Iconic Landmarks and Hidden Gems",
    curr_price: 89699,
    location: "VIETNAM",
    duration: "9 nights 10 days tour",
    image: vietnam3,
  },
  {
    direct: "/Singapore4n5d",
    title: "Singapore Escapes: A Journey through the Vibrant Lion City",
    curr_price: 44699,
    location: "SINGAPORE",
    duration: "4 nights 5 days tour",
    image: singapore,
  },
  {
    home: 3,
    Name: "Singapore",
    location: "SINGAPORE",
    title: "A Journey of Cultural Marvels",
    // title: "Unforgettable Singapore Adventure with Luxurious 2-Night Cruise",
    duration: "7 Days & 6 Nights",
    rating: "4.8/5",
    cut_price: 63900,
    curr_price: 56699,
    // curr_price: 59699,
    direct: "/Singapore6n7d",
    save: 7201,
    image: "https://snowtailescapes.com/images/card/singapore6n7ds.webp",
    country: "singapore",
  },
  {
    direct: "/Singapore_Malaysia",
    title: "Singapore & Malaysia Escapes: A Journey of Cultural Marvels",
    curr_price: 56999,
    location: "SINGAPORE & MALAYSIA",
    duration: "6 nights 7 days tour",
    image: singapore2,
  },
  {
    id: 1,
    title: "Malaysian Marvels - Kuala Lumpur, Penang & Langkawi Escape",
    Name: "Malaysia",
    location: "MALAYSIA",
    duration: "7 Days & 6 Nights",
    rating: "4.8/5",
    cut_price: 39500,
    curr_price: 33999,
    save: 5501,
    direct: "/Malaysia",
    image: "https://snowtailescapes.com/images/card/Malaysia.webp",
    freeVisa: 2,
    country: "malaysia",
  },
  {
    direct: "/Switzerland5n6d",
    title: "Swiss Splendor: A Glimpse of Switzerland Escape",
    curr_price: 97999,
    location: "SWITZERLAND",
    duration: "5 nights 6 days tour",
    image: swit,
  },
  {
    direct: "/France-Italy",
    title: "Experience the Best of Paris & Rome",
    curr_price: 85699,
    location: "FRANCE & ITALY",
    duration: "4 nights 5 days tour",
    image: france,
  },
  {
    direct: "/Greece7n8d",
    title: "Greece Odyssey: An 8-Day Escape",
    curr_price: 139699,
    location: "GREECE",
    duration: "7 nights 8 days tour",
    image: greece,
  },
  {
    title: "Jewel Of Indian Ocean",
    location: "SRI LANKA",
    Name: "Sri Lanka",
    duration: "7 Days & 6 Nights",
    rating: "4.8/5",
    cut_price: 44500,
    curr_price: 38699,
    save: 5801,
    direct: "/SriLanka6n7d",
    image: "https://snowtailescapes.com/images/card/lanka.webp",
    freeVisa: 5,
    country:"sri-lanka",
  },
  {
    direct: "/Dubai3n4d",
    title: "Dubai The City Of Wonders",
    curr_price: 25899,
    location: "DUBAI",
    duration: "3 nights 4 days tour",
    image: dubai,
  },
  {
    home: 4,
    Name: "Dubai",
    location: "DUBAI",
    title: "A Journey of Luxury and Wonder",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 69500,
    curr_price: 58899,
    save: 10601,
    direct: "/Dubai5n6d",
    image: "https://snowtailescapes.com/images/card/Dubai5n6dS.webp",
    country: "uae",
  },
  {
    title: "Wonders of Nepal: The Heart of the Himalayas",
    Name: "Nepal",
    location: "NEPAL",
    duration: "4 Days & 3 Nights",
    rating: "4.8/5",
    cut_price: 39500,
    curr_price: 33999,
    // curr_price: 54699,
    save: 5501,
    direct: "/Nepal",
    image: "https://snowtailescapes.com/images/card/nepal.webp",
    freeVisa: 1,
    country: "nepal",
  },
  {
    direct: "/Australia7d6n",
    title: "Best of Australia",
    Name: "Sydney",
    curr_price: 88980,
    location: "SYDNEY",
    duration: "7 nights 6 days tour",
    image: australia,
    country:"australia",
  },
  {
    direct: "/Japan",
    title: "Best of Japan | From Ancient Shrines to Futuristic Skylines",
    curr_price: 99999,
    location: "KYOTO",
    duration: "9 nights 10 days tour",
    image: japan,
  },
  {
    direct: "/Japan5n6d",
    title: "Discover the Wonders of Japan: A Cultural and Scenic Adventure",
    curr_price: 99999,
    location: "KYOTO",
    duration: "5 nights 6 days tour",
    image: japan2,
  },
  {
    direct: "/Philipenes",
    title: "Discover the Wonders of the Philippines",
    curr_price: 99999,
    location: "MANILA",
    duration: "7 nights 8 days tour",
    image: philipenes,
  },
  {
    home: 5,
    Name: "Almaty",
    location: "ALMATY",
    title: "Central Asian Gem",
    duration: "9 Days & 8 Nights",
    // duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 41699,
    curr_price: 34699,
    // curr_price: 59099,
    save: 7000,
    direct: "/Almaty",
    image: "https://snowtailescapes.com/images/card/almaty.webp",
    freeVisa: 4,
    country: "kazakhstan"
  },
  {
    title: "Experience Jewels of Thailand",
    Name: "Thailand",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 36999,
    curr_price: 29999,
    save: 7000,
    direct: "/Thailand6d5n",
    image: "https://snowtailescapes.com/images/card/thailand5n6ds.webp",
    freeVisa: 3,
    country: "thailand",
  },
];

export const domesticPackages = [
  {
    direct: "/tour/Rajasthan",
    title: "The Incredible Gateway Rajasthan",
    location: "RAJASTHAN",
    curr_price: 34399,
    image: rj1,
    duration: "7 Nights and 8 Days tour",
  },
  {
    direct: "/tour/Rajasthan4n5d",
    title: "Journey Of majesty",
    location: "RAJASTHAN",
    duration: "4 Nights and 5 Days tour",
    curr_price: 19999,
    image: rj2,
  },
  {
    direct: "/Rajasthan5n6d",
    title: "Explore Sand Tails",
    location: "RAJASTHAN",
    curr_price: 25899,
    duration: "5 Nights and 6 Days tour",
    image: rj3,
  },
  {
    Name: "Gujarat",
    location: "GUJARAT",
    title: "Monument of Pride",
    duration: "4 Days & 3 Nights",
    rating: "4.8/5",
    cut_price: 23199,
    curr_price: 16499,
    save: 6700,
    direct: "/Gujarat3n4d",
    image: "https://snowtailescapes.com/images/card/gujarat1.webp",
    budget: 4,
     country:"india"
  },
  {
    direct: "/Gujarat4n5d",
    title: "Gujarat’s Coastal Charms and Wildlife Wonders",
    location: "GUJARAT",
    curr_price: 20999,
    duration: "4 Nights and 5 Days tour",
    image: gujarat2,
  },
  {
    home: 1,
    Name: "Kashmir",
    location: "KASHMIR",
    title: "Adventure Meet Serenity",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 28700,
    curr_price: 26700,
    save: 2000,
    direct: "/Kashmir5n6d",
    image: "https://snowtailescapes.com/images/card/kashmir1.webp",
    country:"india"
  },
  {
    home: 2,
    Name: "Kashmir",
    location: "KASHMIR",
    title: "Experience Paradise On Earth",
    duration: "4 Days & 3 Nights",
    rating: "4.8/5",
    cut_price: 25900,
    curr_price: 18499,
    save: 7401,
    direct: "/Kashmir3n4d",
    image: "https://snowtailescapes.com/images/card/kashmir2.webp",
     country:"india"
  },
  {
    home: 3,
    Name: "Ladakh",
    location: "LADAKH",
    title: "Thrilling Leh Ladakh",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 41999,
    curr_price: 29999,
    save: 12000,
    direct: "/Ladakh5n6d",
    image: "https://snowtailescapes.com/images/card/ladakh.webp",
     country:"india"
  },
  {
    home: 4,
    Name: "Gangtok & Darjeeling",
    location: "SIKKIM",
    title: "The Abode of Clouds",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 50199,
    curr_price: 35799,
    save: 14400,
    direct: "/Sikkim5n6d",
    image: "https://snowtailescapes.com/images/card/sikkim.webp",
     country:"india"
  },
  {
    direct: "/Meghalaya5n6d",
    title: "Meghalaya - Discover The Magic",
    duration: "5 nights and 6 days tour",
    location: "MEGHALAYA",
    curr_price: 32799,
    image: meghalaya,
  },
  {
    direct: "/Kerala5n6d",
    title: "Experience God’s Own Country",
    location: "KERALA",
    curr_price: 25499,
    duration: "5 nights and 6 days tour",
    image: kerala,
  },
  {
    Name: "Manali",
    location: "MANALI",
    title: "A Himalayan Heaven",
    duration: "4 Days & 3 Nights",
    rating: "4.8/5",
    cut_price: 22399,
    curr_price: 15999,
    save: 6400,
    direct: "/Manali3n4d",
    image: "https://snowtailescapes.com/images/card/manali.webp",
    budget: 3,
     country:"india"
  },
  {
    home: 5,
    Name: "Himachal Pradesh",
    location: "SHIMLA & MANALI",
    title: "Sleep In Natures Lap",
    duration: "6 Days & 5 Nights",
    rating: "4.8/5",
    cut_price: 28700,
    curr_price: 26700,
    // curr_price: 24500,
    save: 2000,
    direct: "/Shimla5n6d",
    image: "https://snowtailescapes.com/images/card/shimla5n6d.webp",
     country:"india"
  },
  {
    direct: "/Shimla9n10d",
    title: "Instagrammable Himachal",
    location: "SHIMLA , MANALI , DHARAMSHALA AND DALHOUSIE",
    image: shimla2,
    curr_price: 45999,
    duration: "9 nights and 10 days tour",
  },
  {
    Name: "Kasol",
    location: "KASOL",
    title: "Land of Creamy Flavors",
    duration: "3 Days & 2 Nights",
    rating: "4.8/5",
    cut_price: 15399,
    curr_price: 10999,
    save: 4400,
    direct: "/Kasol2n3d",
    image: "https://snowtailescapes.com/images/card/kasol.webp",
    budget: 1,
     country:"india"
  },
  {
    id: 1,
    Name: "Mussoorie & Rishikesh",
    location: "UTTRAKHAND",
    title: "A Journey to the Queen of Hills",
    duration: "4 Days & 3 Nights",
    rating: "4.8/5",
    cut_price: 22399,
    curr_price: 15999,
    save: 6400,
    direct: "/Uttrakhand",
    image: "https://snowtailescapes.com/images/card/masoorie.webp",
    budget: 2,
     country:"india"
  },
  {
    home: 6,
    Name: "Andaman",
    title: "A Journey to Serenity",
    location: "ANDAMAN & NICOBAR",
    duration: "5 Days & 4 Nights",
    rating: "4.8/5",
    cut_price: 44799,
    curr_price: 31988,
    save: 12811,
    direct: "/Andaman",
    image: "https://snowtailescapes.com/images/card/andaman.webp",
     country:"india"
  },
  {
    direct: "/lonavala3n4d",
    title: "Nature's Bliss in Lonavala: A Relaxing Escape",
    curr_price: 31988,
    duration: "3 nights and 4 days tour",
    location: "Mumbai",
    image: andaman,
  },
  {
    direct: "/lonavala4n5d",
    title: "Nature's Bliss in Lonavala: A Relaxing Escape",
    curr_price: 31988,
    duration: "4 nights and 5 days tour",
    location: "Mumbai",
    image: andaman,
  },
  {
    direct: "/dharamshala",
    title: "Unwind in Dharamshala: Peaceful Getaway in the Mountains",
    curr_price: 31988,
    duration: "5 nights and 6 days tour",
    location: "Dharamshala",
    image: andaman,
  },
  {
    direct: "/dharamshala",
    title: "Spiti Valley Expedition: The Land of Monasteries and Mystique",
    curr_price: 31988,
    duration: "7 nights and 8 days tour",
    location: "Himachal Pradesh",
    image: andaman,
  },
];

const budgetCards = [];
