name: Deploy to EC2

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - main  
    types:
      - closed  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies and restart frontend
      run: |
        ssh -v -q -o StrictHostKeyChecking=no root@${{ secrets.SNOWTAIL_IP }} << 'EOF'
          set -e
          export PATH=$PATH:/root/.nvm/versions/node/v20.16.0/bin
          cd ./frontend/snowtail_frontend
          echo "Frontend working directory:"
          pwd
          git reset --hard
          git pull
          npm install
          npm run build
        EOF
