name: Deploy to EC2

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH Key (Optional, for Debugging)
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies and restart frontend
      run: |
        ssh -v -q -o StrictHostKeyChecking=no root@${{ secrets.SNOWTAIL_IP }} << 'EOF'
          set -e
          cd ~/frontend/snowtail_frontend
          git reset --hard
          git pull
          npm install
          npm run build
        EOF
