name: Deploy to EC2

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
    types:
      - closed  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Install dependencies and restart PM2
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.82.112.235.224 }} "cd /root/frontend/snowtail_frontend && git reset --hard && git pull && npm install && npm run build && pm2 restart 3"
